# -*- coding: utf-8 -*-
"""nlp_lab_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BrxvKrnKANuJ-8VJ5UqOqt6JCr8qXJ0Z
"""

!pip install pymorphy2

import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')
from nltk import sent_tokenize
import pymorphy2
from nltk.corpus import stopwords
nltk.download('stopwords')
import re

from google.colab import drive
drive.mount('/content/drive')

txt = open("/content/drive/MyDrive/text.txt")
m = pymorphy2.MorphAnalyzer()
def define_tag(word):
    w = m.parse(word)[0]
    tag = w.tag
    return tag
text = txt.read()
text = re.sub(r'[^\w\s]', '', text)
stop_words = set(stopwords.words('russian'))
tokens = [token for token in word_tokenize(text) if token.lower() not in stop_words]

m = pymorphy2.MorphAnalyzer()
for token in tokens:
  define_tag(token)
pairs = []
for i in range(len(tokens) - 1):
    current_word = tokens[i]
    next_word = tokens[i + 1]
    tag1 = define_tag(current_word)
    tag2 = define_tag(next_word)
    if (((tag1.POS in ['NOUN', 'ADJF']) or (tag2.POS in ['NOUN', 'ADJF'])) and (tag1.gender == tag2.gender) and (tag1.number == tag2.number) and (tag1.case == tag2.case)):
        pairs.append((m.parse(current_word)[0].normal_form, m.parse(next_word)[0].normal_form))

for pair in pairs:
    print(f"{pair[0]}, {pair[1]}")